# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_added', models.CharField(max_length=45)),
                ('item_created', models.CharField(max_length=45)),
                ('user', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('date_added', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
